default: &default
  adapter: postgresql
  encoding: unicode
  database: blog
  pool: 5
  username: postgres
  password: postgres
  host: db

development:
  <<: *default
  database: db/development

test:
  <<: *default
  database: db/test

production:
  <<: *default
  database: db/production