version: '3'
services:
  db:
    image: postgres
    container_name: db
    volumes:
      - ./config/postgres-data:/var/lib/postgresql/data

    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    ports:
      - "5432:5432"


  rails:
    build:
      context: "."
      dockerfile: "Dockerfile_rails"
    container_name: rails
    depends_on:
      - db
    environment:
      RUBYOPT: "-W:no-deprecated -W:no-experimental"
      RAILS_MASTER_KEY: "a667717bf0a47475b0582547379c816d"
        # "${RAILS_MASTER_KEY}"
    tty: true
    command: rails server -b 0
    ports:
      - "3000:3000"

  vue:
    build:
      context: "."
      dockerfile: "Dockerfile_vue"
    container_name: vue
    volumes:
      - ./volume:/home/edimossilva/development/volume
    ports:
      - "8080:8080"
    tty: true
    command: bash
    working_dir: /home/edimossilva/development/volume/blog-frontend
    depends_on:
      - rails
# docker-compose build
# docker-composer run rails rake db:create
# docker-compose up -d
# localhost:3000