FROM node:10

# set working directory
WORKDIR /app

RUN yarn global add @vue/cli

# install and cache app dependencies
COPY ./volume/blog-frontend/package.json /app/package.json
COPY ./volume/blog-frontend/yarn.lock /app/yarn.lock

#install dependencies
RUN yarn install

